RubyProjects/rails_projects/alpha-blog/config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'

end

RubyProjects/rails_projects/alpha-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end
	def new
		@article = Article.new
	end 
	def create 
	    @article = Article.new(article_params)
		if @article.save 
			flash[:notice] = "Article was created"
			redirect_to article_path(@article)
		else
			render :new #validations failed
		end
	end
	def show
		@article = Article.find(params[:id])
	end
	def edit
		@article = Article.find(params[:id])
	end
	def update 
		@article = Article.find(params[:id])
	    if @article.update(article_params) 
			redirect_to article_path(@article)
		else 
			render'edit'
		end
	end



	private
		def article_params 
			params.require(:article).permit(:title, :description)
		end


end

RubyProjects/rails_projects/alpha-blog/app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<p><%= link_to "Create new article", new_article_path %></p>
<table>
	<tr>
		<th>Title</th>
		<th>Description</th>
	</tr>	
	<% @articles.each do |article| %>
	<tr>
		<td><%= article.title %></td>
		<td><%= article.description %></td>
		<td><%= link_to 'Edit', edit_article_path(article) %></td>
		<td><%= link_to 'Show', article_path(article) %></td>
	</tr>
	<% end %>
</table>

RubyProjects/rails_projects/alpha-blog/app/views/articles/new.html.erb
<h1> Create an article </h1>

<% if @article.errors.any? %>
<h2> The following errors prevented the article from getting created</h2>
<uL>
	<% @article.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>
<p>
		<%= f.label :title %> <br/>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %> <br/>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.submit %>
	</p>

<% end %>

<%= link_to "Back to articles listing", articles_path %>

RubyProjects/rails_projects/alpha-blog/app/views/articles/show.html.erb
<h2>Showing selected articles</h2>


<p> Title: <%= @article.title %> </p>
<p> Description <%= @article.description %>
</p>

<%= link_to "Back to articles listing", articles_path %>

RubyProjects/rails_projects/alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |name, msg| %>
		<ul>
			<li> <%= msg %> </li>
		</ul>
	<% end %>
<%= yield %>

</body>
</html>

RubyProjects/rails_projects/alpha-blog/app/views/pages/home.html.erb
<h1> hey I am the homepage </h1>
<%= link_to 'About', pages_about_path %>